package:
  name: sieve
  version: "1.0.0"

source:
  git_rev: v1.0.0
  git_url: https://github.com/ehatton/sieve.git

requirements:
  host:
    - python >=3.6
    - click
    - setuptools

  run:
    - python >=3.6
    - click
    - setuptools

build:
  noarch: python
  entry_points:
    - sieve = sieve.cli:main

test:
  commands:
    - sieve --help
  imports:
    - sieve

about:
  home: https://github.com/ehatton/sieve
  license: MIT
  license_file: LICENSE 
